apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patient-health-backend
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: patient-health
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://github.com/alimire/patient-health-backend.git'
    targetRevision: dev
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true